service:
  externalPort: 80
  internalPort: 80
postgresql:
  enabled: false
hpa:
  enabled: true
livenessProbe:
  path: "/health"
readinessProbe:
  path: "/health"
resources:
  limits:
    cpu: 100m
    memory: 512Mi
podDisruptionBudget:
  enabled: true
ingress:
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
#    nginx.ingress.kubernetes.io/rewrite-target: /
#    nginx.ingress.kubernetes.io/proxy-read-timeout: '3600'
#    nginx.ingress.kubernetes.io/proxy-send-timeout: '3600'
#    nginx.ingress.kubernetes.io/configuration-snippet: |
#      proxy_set_header Upgrade "websocket";
#      proxy_set_header Connection "Upgrade";
