import COUNTRIES from "../../helpers/countries";

const bookingFormModel = {
    formInitialValues: {
        numberOfPeople: 1,
        product: 0,
        testType: {},
        city: '',
        timezone: '',
        travelDate: new Date(),
        travelTime: new Date(),
        passengers: [
            {
                firstName: '',
                lastName: '',
                email: '',
                phone: '',
                countryCode: COUNTRIES.find(({ country }) => country === 'United Kingdom'),
                dateOfBirth: null,
                ethnicity: '',
                sex: 'Female',
                passportNumber: '',
            },
        ],
        appointmentDate: new Date(),
        selectedSlot: null,
        landingDate: new Date(),
        landingTime: new Date(),
        flightNumber: '',
    },
    formField: {
        numberOfPeople: {
            name: 'numberOfPeople',
            label: 'Number of People',
            id: 'number-of-people',
            type: 'number',
            required: true,
        },
        product: {
            name: 'product',
            label: 'Select the test you are booking for',
            id: 'product',
            type: 'text',
            required: true,
        },
        countryCode: {
            name: 'Country Code',
            label: 'Choose a country code',
            id: 'country-code',
            type: 'text',
            required: true,
        },
        city: {
            name: 'city',
            label: 'Select Country of Origin',
            id: 'city',
            type: 'text',
            placeholder: 'Select Country of Origin',
            required: true,
        },
        pcrTest: {
            name: 'pcrTest',
            label: 'PCR Tests',
            id: 'pcr-kit',
            type: 'number',
            required: true,
        },
        travelDate: {
            name: 'travelDate',
            label: 'Select Departure Date',
            placeholder: 'DD/MM/YYYY',
            required: true,
        },
        travelTime: {
            name: 'travelTime',
            label: 'Select Departure Time',
            placeholder: '00:00 AM/PM',
            required: true,
        },
        landingDate: {
            name: 'landingDate',
            label: 'Select Landing Date',
            placeholder: 'DD/MM/YYYY',
            required: true,
        },
        landingTime: {
            name: 'landingTime',
            label: 'Select Landing Time',
            placeholder: '00:00 AM/PM',
            required: true,
        },
        flightNumber: {
            name: 'flightNumber',
            label: 'Flight Number',
            placeholder: 'EY402',
            id: 'flight-number',
            type: 'text',
            required: true,
        },
        firstName: {
            name: 'firstName',
            label: 'First Name',
            id: 'first-name',
            type: 'text',
            required: true,
        },
        lastName: {
            name: 'lastName',
            label: 'Last Name',
            id: 'last-name',
            type: 'text',
            required: true,
        },
        email: {
            name: 'email',
            label: 'Email Address',
            id: 'email',
            type: 'email',
            required: true,
        },
        phone: {
            name: 'phone',
            label: 'Phone number',
            id: 'phone',
            type: 'text',
            required: true,
        },
        dateOfBirth: {
            name: 'dateOfBirth',
            label: 'Date Of Birth',
            id: 'date-of-birth',
            placeholder: 'dd/mm/yyyy',
            emptyLabel: 'dd/mm/yyyy',
            required: true,
        },
        ethnicity: {
            name: 'ethnicity',
            label: 'Ethnicity',
            id: 'ethnicity',
            type: 'text',
            required: true,
        },
        sex: {
            name: 'sex',
            label: 'Sex',
            required: true,
        },
        passportNumber: {
            name: 'passportNumber',
            label: 'Passport Number',
            id: 'passport-number',
            type: 'text',
            required: true,
        },
        appointmentDate: {
            name: 'appointmentDate',
            label: 'Select Date',
        },
        selectedSlot: {
            name: 'selectedSlot',
            label: 'Select Time',
        },
    },
};

export default bookingFormModel;
