
//MAKING A CUSTOMIZED ORDER OF ANY PRODUCT
//PLEASE USE customize_test.json FOR TEST SETUP
import { test_data } from '../../fixtures/customize_test.js'
import OrderPage from '../../page_objects/OrderPage.js'
import { get_products } from '../../support/utils/utils.js';

const Order = new OrderPage(test_data)
let products_ids = Order.get_products_ids();
console.log(products_ids)

let source = test_data[2].source;

before('get products data', () => {
	Order.get_all_products_data()
})


describe(`B2C - Purchasing ${source} product`, () => {

	it('Order page for the product is loaded successfully', () => {
		let link = `https://airportal-staging.dochq.co.uk/rapid-antigen-testing-order?source=${source}`

		cy.intercept({ method: 'GET', url: link, }).as('order_page')
		cy.visit(link); cy.wait(2000); cy.reload()
		cy.wait('@order_page')

		// Assert products checkout page
		cy.get('@order_page').should(req => { expect(req.response.statusCode).eq(200) })
		cy.wait(2000)
	})


	it('Pessenger details can be submitted', () => {
		// Random user data is generated 
		Order.fill_account_details(source, test_data[1].email)

		cy.get('.green').contains('Next').click()
		cy.wait(1500)
	})


	it('Shipping address and phone number details can be submitted', () => {
		// Random data is generated by default, 
		// to customise - enter arguments respectively: country_code, phone, postcode, address, city, country
		Order.fill_shipping_address(source, test_data[1].country_code, test_data[1].phone) // only random UK number is supported

		cy.get('.green').contains('Next').click()
		cy.wait(1500)
	})


	it(`Voucher code for ${source} is valid`, () => {
		// Discount code
		let voucher = (source == "amex-it" ? "AXPIT330033" : test_data[2].voucher)

		cy.get('input[name="discountCode"]').fill(voucher)
		cy.pause()

		cy.get('.green').contains('Next').click();
		cy.wait(1500)
	})

	it('Purchasing confirmation and order data save', () => {
		cy.get('div.row.no-margin > b').should('have.text', "Thank you for completing your purchase!")

		Order.write_order_data() //cypress/fixtures/order_list.json
		Order.write_user_data()  //cypress/fixtures/user.json
	})
})