# This is a basic workflow that is manually triggered

name: Deploy to production

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch
env:
  CI_REGISTRY_PASSWORD: ${{ secrets.CI_REGISTRY_PASSWORD }}
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  NAMESPACE: myhealth
  IMAGE: myhealth

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  deploy-to-production:
    name: Deploy to production
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    # Runs a single command using the runners shell
    - name: Deploy
      env:
        KUBECONTEXT: 'gke_dochq-production_europe-west2_dochq'
      run: |-
        $(cd deploy/production/ && kustomize edit set image microservice=gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA) && \
        kustomize build ./deploy/production | kubectl apply --context $KUBECONTEXT --namespace $NAMESPACE -o yaml --wait=true -f -

